### ISSUE TITLE
will heading add support for multi headers?

### ISSUE THREAD

**Issue by hyaray** [Vinzent03/obsidian-advanced-uri#108]
Hi, I got a bit problem:
maybe there's more `#sub` in file, so we need `#B#sub` to goto what we exactly want.
will format like `obsidian://advanced-uri?vault=<your-vault>&filepath=my-file&heading=B#subl` be supported?

Best Regards!!

**Comment by megclaypool** [comment]
One trick I've got is to set up unique comments in front of my non-unique sub-headings. In my weekly file, I use the same headings for each day, but I preface it with the date in a comment. So instead of just "Notes" I've got `%%20230201%%Notes`. Obsidian Advanced URI sees it as "20230201 Notes". Meanwhile, I've got a CSS snippet that hides comments in live preview unless I'm editing that line, so I just see it as "Notes".

```css
/* Hide comments except on active line */
.cm-active .cm-comment {
  display: inline;
}

.cm-comment {
  display: none;
}

/* Hide block ids except on active line */
.markdown-source-view.mod-cm6 .cm-active span.cm-blockid {
  display: inline-block;
}

.markdown-source-view.mod-cm6 span.cm-blockid {
  display: none;
}

```

**Comment by hyaray** [comment]
I want to open obsidian with focused title.
if I added comments text, I will not know what I added at the front.

Thanks for your skill and `css` codes!!
It's very useful on some other cases.

**Comment by megclaypool** [comment]
One trick I've got is to set up unique comments in front of my non-unique sub-headings. In my weekly file, I use the same headings for each day, but I preface it with the date in a comment. So instead of just "Notes" I've got `%%20230201%%Notes`. Obsidian Advanced URI sees the comment, so it's a unique heading. Meanwhile, I've got a CSS snippet that hides comments in live preview unless I'm editing that line, so I just see it as "Notes".

```css
/* Hide comments except on active line */
.cm-active .cm-comment {
  display: inline;
}

.cm-comment {
  display: none;
}

/* Hide block ids except on active line */
.markdown-source-view.mod-cm6 .cm-active span.cm-blockid {
  display: inline-block;
}

.markdown-source-view.mod-cm6 span.cm-blockid {
  display: none;
}

```
